name: HyperTraPS
channels:
  - vivianleung  # for pmodeltest
  - etetoolkit
  - conda-forge
  - defaults
dependencies:
  # - python=3
  - numpy=1.21
  - scipy=1.7
  - matplotlib=3.5
  - pandas=1.3
  - networkx=2.6
  - statsmodels=0.13
  - ete3=3.1
  - seaborn=0.11
  - jupyterlab
  - pygraphviz
  - pmodeltest
  - ete_toolchain
