#!/usr/bin/env python3

# convert_vcflike_to_ht_data.py

# Convert tsv generated via. bcftools query to ht data type

# Vivian Leung

# Created:      14 Jan 2024
# Last updated: 14 Jan 2024


import argparse
import pandas as pd


parser = argparse.ArgumentParser(
    description=(
        "Convert VCF-like TSV of features (e.g. generated by bcftools query) "
        "to HyperTraPS data format for further conversion by convert_data_to_transitions.py"
    )
)

parser.add_argument(
    "-i", "--infile", type=str,
    help=("Input TSV with index as feature ids, column headers as sample "
          "names, values as binary")
)
parser.add_argument('-o', "--outfile",
                    help="Output file. Default infile with 'ht.csv' suffix")

args = parser.parse_args()


if args.outfile is not None:
    outfile = args.outfile
    
else:
    outfile = f"{args.infile.rpartition('.')[0]}.ht.csv"

ht = (
    pd.read_csv(args.infile, sep='\t', index_col=0)
    .rename_axis(index=None, columns='Isolate')
    .T
)
ht.to_csv(outfile)

print("Output saved to", outfile)
